name: Release Daggerheart SRD Module

on:
  push:
    tags:
      - "v*" # Triggers on any tag starting with 'v' (e.g., v1.0.0, v2.1.3)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Gulp globally
        run: npm install -g gulp-cli

      - name: Get tag name and version information
        id: tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set the version the module file
        run: npm run version
        env:
          RELEASE_VER: ${{ steps.tag.outputs.version }}

      - name: Build the release files
        run: npm run release

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/module.json
            ./dist/module.zip
          name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
